version: "3.7"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./public/static:/usr/share/nginx/static:ro
      - ./nginx-certbot/data/nginx:/etc/nginx/conf.d
      - ./nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ./nginx-certbot/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
    networks:
      - postech-in-the-sky

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ./nginx-certbot/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - postech-in-the-sky

  app:
    build: .
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - postech-in-the-sky

  db: 
    image: mysql:8
    restart: unless-stopped
    expose:
      - "3306"
    cap_add: 
      - SYS_NICE
    command:
      - --max_connections=501
      - --wait_timeout=30
    volumes:
      - db:/var/lib/mysql
    env_file: .env.production.local
    networks:
      - postech-in-the-sky

volumes:
    db:

networks:
  postech-in-the-sky:
    driver: bridge
